feat: Bittensor BlockchainManager using commitments of knowledge
ggleszczynski/bt-ddos-shield pull request #1
Opened 2024-12-20 12:56 UTC by zyzniewski-reef

2025-01-05 22:35 UTC, mpnowacki-reef requested changes

2025-01-05 22:35 UTC, mpnowacki-reef commented on bt_ddos_shield/blockchain_manager.py
> +        metadata = get_metadata(
this has retires in it, which is awesome, but i am not sure the retries being ther are part of any public API contract and if they aren't then we should add tests with a mock subtensor that fails a few times before finally returning the thing. If that's not too much hassle.

2025-01-05 22:35 UTC, mpnowacki-reef commented on bt_ddos_shield/blockchain_manager.py
> +        except TypeError:
what does this catch, actually? metadata being None and hex_data not being a string. That's not very comprehensive. Also `try: ... except TypeError: ...` is sth that can start trigerring due to a bug, i don't aprticularly like that check. I think an explicit one would be much better, i.e. pydantic validation for instance.

2025-01-05 22:35 UTC, mpnowacki-reef commented on bt_ddos_shield/blockchain_manager.py
> +        if hotkey != self.wallet.hotkey.ss58_address:
what' the point of this `hotkey` argument then?

2025-01-05 22:35 UTC, mpnowacki-reef commented on bt_ddos_shield/blockchain_manager.py
> +        publish_metadata(
does this do retires? writes to subtensor are notoriosuly faulty. Also they like to hang forever, we should facilitate that.

2025-01-05 22:35 UTC, mpnowacki-reef commented on tests/test_blockchain_manager.py
> +    def test_get(self):
what? are these pytest tests put in some class?

2025-01-06 19:25 UTC, zyzniewski-reef commented on bt_ddos_shield/blockchain_manager.py
> +        except TypeError:
tbh it was copied from [get_commitment](https://github.com/opentensor/bittensor/blob/master/bittensor/core/subtensor.py#L1072-L1094)

2025-01-06 19:26 UTC, zyzniewski-reef commented on bt_ddos_shield/blockchain_manager.py
> +        if hotkey != self.wallet.hotkey.ss58_address:
well it's part of `AbstractBlockchainManager` interface

2025-01-06 19:27 UTC, zyzniewski-reef commented on tests/test_blockchain_manager.py
> +    def test_get(self):
was just following convention already used in other tests ... https://github.com/bactensor/bt-ddos-shield/blob/master/tests/test_miner_shield.py

2025-01-06 20:00 UTC, zyzniewski-reef commented on bt_ddos_shield/blockchain_manager.py
> +        publish_metadata(
it's decorated with `ensure_connected` """Decorator ensuring the function executes with an active substrate connection."""

2025-01-06 20:36 UTC, mpnowacki-reef requested changes

2025-01-06 20:36 UTC, mpnowacki-reef commented on bt_ddos_shield/blockchain_manager.py
> +        except TypeError:
That's not a convincing argument for it. In any case, what's the license situation? can you copy a whole function wihtout mentioning it in a license? Why not call the function? and if the function cannot be called i would still argue a better validatation is necessary

2025-01-06 20:36 UTC, mpnowacki-reef commented on tests/test_blockchain_manager.py
> +    def test_get(self):
The guy who did is a highly skilled engineer who is learning python and its ecosystem right now. He should be learning conventions from you and the other way around.

2025-01-06 20:36 UTC, mpnowacki-reef commented on bt_ddos_shield/blockchain_manager.py
> +        if hotkey != self.wallet.hotkey.ss58_address:
Well you're part of this project now. I don't have any knowledge of any other implementations of `AbstractBlockchainManager` planned. Unless there's a good case for keeping this argument it should be removed.

2025-01-06 20:36 UTC, mpnowacki-reef commented on bt_ddos_shield/blockchain_manager.py
> +        publish_metadata(
and what if it isn't? does it throw or retry? Also such a decorator is surely not atomic. And what about hanging?

2025-01-07 08:34 UTC, zyzniewski-reef commented on bt_ddos_shield/blockchain_manager.py
> +        if hotkey != self.wallet.hotkey.ss58_address:
Paweł mentioned we/someone may implement support for other blockchains. I think it's good to keep this parameter to be forward-compatible just in case.

2025-01-07 09:28 UTC, zyzniewski-reef commented on bt_ddos_shield/blockchain_manager.py
> +        publish_metadata(
added unittest for testing retries of `get_metadata` and `publish_metadata`

2025-01-07 09:31 UTC, grzegorz-leszczynski-reef commented on bt_ddos_shield/blockchain_manager.py
> +        if hotkey != self.wallet.hotkey.ss58_address:
Hmm, but other blockchains can have different API, without anything like hotkey. I added it to interface, but if it is not needed (as we have wallet) I think we should remove it.

2025-01-07 09:33 UTC, zyzniewski-reef commented on bt_ddos_shield/blockchain_manager.py
> +        except TypeError:
> can you copy a whole function wihtout mentioning it in a license?

Just refactored the function.

> Why not call the function?

Original function tried to decoded raw bytes to string - our API works on bytes directly

> and if the function cannot be called i would still argue a better validatation is necessary

Data schema should be valid as it comes from Rust runtime:
- https://github.com/opentensor/subtensor/blob/c1c25e28d44dea4a0062628a71283760839cbd00/pallets/commitments/src/types.rs#L294-L296
- https://github.com/opentensor/subtensor/blob/c1c25e28d44dea4a0062628a71283760839cbd00/pallets/commitments/src/types.rs#L39-L56

2025-01-07 09:33 UTC, grzegorz-leszczynski-reef commented on bt_ddos_shield/blockchain_manager.py
> +        publish_metadata(
If it fails, it will be retried by shield worker. But hanging (if possible) needs to be handled somehow.

2025-01-07 09:43 UTC, grzegorz-leszczynski-reef commented on tests/test_blockchain_manager.py
> +    def test_get(self):
Hehe :P Anyway I copied this convention from Hiroyuki (if I remember his name correctly). Point taken.

2025-01-07 09:44 UTC, zyzniewski-reef commented on bt_ddos_shield/blockchain_manager.py
> +        if hotkey != self.wallet.hotkey.ss58_address:
just changed `AbstractBlockchainManager` API

2025-01-07 09:48 UTC, zyzniewski-reef commented on bt_ddos_shield/blockchain_manager.py
> +        publish_metadata(
from what I see requests are made from ThreadPool and has `EXTRINSIC_SUBMISSION_TIMEOUT` - what type of hanging are we talking about?

2025-01-07 10:16 UTC, grzegorz-leszczynski-reef commented on bt_ddos_shield/blockchain_manager.py
> -        self.put(self.miner_hotkey, self.address_serializer.serialize(address))
I think, we should remove miner_hotkey from this class completely

2025-01-07 13:46 UTC, mpnowacki-reef commented on bt_ddos_shield/blockchain_manager.py
> +        publish_metadata(
setting weights, for exxample, sometimes just hangs forever and never returns

2025-01-07 13:48 UTC, mpnowacki-reef commented on bt_ddos_shield/blockchain_manager.py
> +        except TypeError:
Okay I'm not sure i would rely on that. You can have a breaking (unplanned) change in the subtensor and our code will just start spamming keyerrors or whatever if we don't validate

2025-01-07 16:44 UTC, zyzniewski-reef commented on bt_ddos_shield/blockchain_manager.py
> +        except TypeError:
as part of the refactor I've added `LookupError` handle

2025-01-10 09:53 UTC, mpnowacki-reef approved these changes

2025-01-10 12:25 UTC, merged